### ISSUE TITLE
Blog Post Pages On Mobile

### ISSUE THREAD

**Issue by bkeane15** [disputebills/website#14]
Blog post pages on mobile are displaying in a weird way. Please review.

BK

**Comment by bryanwillis** [comment]
I went through several of the blog pages and cleaned them up within the post as well as added some css fixes. 

**Here's what I did:**
- [Enhanced design of table](https://disputebills.com/the-best-and-worst-states-for-healthcare-in-the-us-2016/) 
- Better [white space and line height on text and images within posts](https://disputebills.com/10-of-the-most-overpriced-prescription-drugs/) within posts
- Darkened some of the text, bold, proportional font sizes
- Added spacing on left and right of page on mobile
- Fixed [video embedded to be responsive](https://disputebills.com/open-enrollment-2017-how-to-find-the-right-health-insurance-plan/)
- Changed [text to list elements](https://disputebills.com/10-of-the-most-overpriced-prescription-drugs/) within posts and added css for numbers
- reduced height of main banner images within posts

Hopefully one of these fixed whatever the weird display was you were referring to, but if not let me know what it is exactly that you're seeing.

**Comment by bryanwillis** [comment]
Brian have you had a chance to take a look to see if it's all working now?

**Comment by bkeane15** [comment]
Looks great, thanks!

BK
