### ISSUE TITLE
Medical Bill Advocate Page

### ISSUE THREAD

**Issue by bkeane15** [disputebills/website#18]
I'd like to change the copy on this page. How do I go about doing that?

BK

**Comment by bkeane15** [comment]
How do I access the source code?

**Comment by bryanwillis** [comment]
[You can change it here by editing and creating a pull request](https://github.com/disputebills/website/blob/master/assets/themes/disputebills-theme/page-advocate.php) 

<img width="1223" alt="screen shot 7" src="https://cloud.githubusercontent.com/assets/4042621/19658938/8bed1046-99ef-11e6-9ad1-c493bf29f969.png">

If you want to change it directly I emailed you an SFTP login, but you'll still need to change it in the above link to avoid the changes getting overridden on an update.

**Comment by bryanwillis** [comment]
Eventually when I get some time I'll make it so this template can be edited in wordpress admin.
