### ISSUE TITLE
Intermediate (Upwork Style Page)

### ISSUE THREAD

**Issue by bkeane15** [disputebills/website#5]

**Comment by bryanwillis** [comment]
Is it good how it is now?

**Comment by bkeane15** [comment]
It's off center but definitely close

BK

**Comment by bkeane15** [comment]
Change the copy to healthcare savings card

**Comment by bryanwillis** [comment]
By offcenter, not sure what you mean... Could you take a screenshot?

**Comment by bkeane15** [comment]
![image](https://cloud.githubusercontent.com/assets/21245180/19525146/9af2a60e-95e5-11e6-8e4e-75be20b104fb.png)

**Comment by bkeane15** [comment]
Shouldn't it be center aligned?

**Comment by bryanwillis** [comment]
Strange, t fine on my end. I tried changing something so hopefully that fixes it for you. If not, what browser are you using?

<img width="1098" alt="screen shot" src="https://cloud.githubusercontent.com/assets/4042621/19525594/18b7a552-95e7-11e6-889e-6c96d1ee95d9.png">

**Comment by bkeane15** [comment]
i was using chrome

**Comment by bryanwillis** [comment]
Strange me too. Are you up to date? Also did my change fix it? You might have to clear your cache...

**Comment by bryanwillis** [comment]
Are we good with this one? You still having those issues?

**Comment by bkeane15** [comment]
Looks good!

BK
